### ISSUE TITLE
I see {error,eaddrinuse}

### ISSUE THREAD

**Issue by saa** [epgsql/epgsql#169]
Sometimes, when i tried open new connection to postgres I got error: `{error,eaddrinuse}`

What I do wrong?

**Comment by saa** [comment]
Probably need to add `{reuseaddr, true}`?

**Comment by seriyps** [comment]
Which options do you use when connecting?

вт, 11 сент. 2018 г., 13:33 Sergey Abramyan <notifications@github.com>:

**Comment by saa** [comment]
What do you mean? I use 3.4.0 version.

**Comment by seriyps** [comment]
I mean arguments for `connect` function (except host and password of course)

вт, 11 сент. 2018 г., 13:53 Sergey Abramyan <notifications@github.com>:

**Comment by saa** [comment]
Only host, password, user, database.

**Comment by seriyps** [comment]
It might be that you are making a lot of short-living outgoing tcp
connections and run out of sockets because of TIME_WAIT.
Try checking `netstat -nt`.

See also
http://erlang.org/pipermail/erlang-questions/2006-December/024315.html

Do you think it might be the reason?
Do you ise any epgsql connection pool?

вт, 11 сент. 2018 г., 14:14 Sergey Abramyan <notifications@github.com>:

**Comment by saa** [comment]
Yes, probably this is reason. Yes, I use pool. But sometimes i need more connections and i start open new. Probably need add `{reuseaddr, true}` to `gen_tcp:connect`?

**Comment by seriyps** [comment]
I think it might make sense to add smth like `socket_opts` option to `conect` instead of just adding this particular one.
But for general case it's for sure not comon to add `reuse_addr` to non-listening socket, I don't think we should add it by-default.
Do ou want to do a PR?

**Comment by saa** [comment]
Yes, after full tests i will add PR.

**Comment by seriyps** [comment]
This should be covered dy #242
