### ISSUE TITLE
Feature: Map null to undefined on decoding

### ISSUE THREAD

**Issue by Xelgun** [epgsql/epgsql#203]
What do you think? Afaik the usage of null atom in Erlang code is much less common and also it's not Elixir-compatible.
We can't handle null to undefined conversion with pluggable datatype codecs because of this lines
https://github.com/epgsql/epgsql/blob/cd3144d88f476b0425ea42319a3f6a8a22c13edf/src/epgsql_wire.erl#L144-L149 (and few others) and also because NULL is not really a PostgreSQL data type.

In jiffy for example we have {null_term, Term} option that cause to return the specified Term instead of null on decoding.

**Comment by seriyps** [comment]
Hi. Yep, I was thinking about this and also think it should be configurable for both encoding and decoding. I think some special option for `connect` would work the best. As alternative - it might be set via epgsql's application env.

Also, my idea was to allow multiple values for null encoding (eg, encode all of `undefined`, `null`, `nil` as `NULL`), but always return one of them when decoding. The simplest way this could be achieved is to provide accepted values as a list and use 1st element of a list when decoding. Eg:

```
epgsql:connect(#{..., null_terms => [undefined, null, nil]})
```

This connection will encode any of `undefined`, `null`, `nil` as NULL, but will decode all `NULL`s as `undefined` because it's 1st element of a list.

Unfortunately, it's not that straightforward to implement (would require separate field in `epgsql_sock`'s state, needs to be bypassed deep into decoder's code stack), so PR is welcome!

**Comment by seriyps** [comment]
Ok, it looks like it might be simplified a bit if `null` handling will be moved from `epgsql_wire` to `epgsql_binary` and `null_terms` will be stored in `#codec.opts`. But still, it would require separate field in `epgsql_sock`s state (not a big problem)

**Comment by seriyps** [comment]
With #212 it is configurable now.
