### ISSUE TITLE
Use of deprecated function (crypto:hmac/3)

### ISSUE THREAD

**Issue by galdor** [epgsql/epgsql#235]
When building epgsql on OTP 23, I get:

```_build/default/lib/epgsql/src/epgsql_scram.erl:129: Warning: crypto:hmac/3 is deprecated and will be removed in OTP 24; use use crypto:mac/4 instead```

I'd like to submit a patch to switch to `crypto:/mac/4`, but this function has only been introduced in OTP 22.1, and I'm not sure which versions epgsql officially supports, and I can't seem to find how to precisely check for the OTP version with the preprocessor.

Would it be ok to drop <22.1 ? If not, do you have a suggestion on how to detect the version at compile time ?

**Comment by seriyps** [comment]
Hi. We definitely don't want to drop support for older versions just because of this deprecated function.

This issue is usually solved by using conditional compilation (see the last example in ["Flow control macros" section]( https://erlang.org/doc/reference_manual/macros.html#flow-control-in-macros)). I would suggest smth like:

```erlang
-ifdef(OTP_RELEASE).
  -if(OTP_RELEASE >= 22).
    ...
  -else.
    ...
  -endif.
-else.
 ...
-endif.
```

Or you can use rebar's `platform_define` feature, eg https://github.com/epgsql/epgsql/blob/b3138f76759750ab5e6202766cb39acd88c8ff54/rebar.config#L1

**Comment by seriyps** [comment]
And for the list of supported versions - the easiest way is usually to check the ones listed in `.travis.yml`

https://github.com/epgsql/epgsql/blob/f8a5acc2e965c185f39150dc9d17bc75448d8a67/.travis.yml#L14-L18
