### ISSUE TITLE
Unable to insert UTF-8 

### ISSUE THREAD

**Issue by Katur7** [epgsql/epgsql#281]
Hi,

I'm having issues inserting a utf-8 string into a varchar field.
I created a table
`CREATE TABLE test
(
    test_text character varying
)`

and tried inserting into it with
`insert into test values ('sævar')`

That works fine.

Then when I try to insert with epgsql I get an error.
I try to insert with this code:
`
{ok, C} = epgsql:connect("localhost", "test_user", "test_pass", []).
`
`
epgsql:equery(C, <<"insert into test ( test_text ) values ($1);">>, [<<"sævar">>]).
`

Then I get the error:
`
{error,{error,error,<<"22021">>,character_not_in_repertoire,
              <<"invalid byte sequence for encoding \"UTF8\": 0xe6 0x76 0x61">>,
              [{file,<<"mbutils.c">>},
               {line,<<"1665">>},
               {routine,<<"report_invalid_encoding">>},
               {severity,<<"ERROR">>},
               {where,<<"unnamed portal parameter $1">>}]}}
`

Are utf-8 strings not supported or am I missing some config or something?

**Comment by seriyps** [comment]
Epgsql for sure supports Unicode (to be precise, for varchar/text it just
sends raw bytes you provide as a parameter directly to the server without
modifying it).

So the problem is most likely in how unicode input is configured, because
you trying to type unicode binaries from the Erlang shell.
For this to work correctly you have to:
* Add "+pc unicode" to erl command (erl +pc unicode)
* Binary literals should state that the binary encoding is utf8 explicitly:
<<"sævar"/utf8>>

**Comment by Katur7** [comment]
Thank you so much.
I was missing stating the utf8 encoding explicitly.
It works great when I add that.
