### ISSUE TITLE
New release for OTP-26 compat

### ISSUE THREAD

**Issue by mworrell** [epgsql/epgsql#285]
@seriyps Now that OTP-26 has been released, can you make a new release and push a new package to Hex?

I expect that would fix an issue with opening a db connection on OTP-26.

**Comment by seriyps** [comment]
Hi. I tried, but CI failed due to not being able to install PostgreSQL on Ubuntu 20.04

https://github.com/epgsql/epgsql/actions/runs/5089552828

It tries to install version 12.14, wille Ubuntu repo has only 12.15. Looks like CI repository is inconsistent (it was updated 24th of May). I'll wait a day or two and if it's not fixed wil lstart looking for work-arounds.

**Comment by seriyps** [comment]
Done!

https://github.com/epgsql/epgsql/releases/tag/4.7.1
https://hex.pm/packages/epgsql/4.7.1

**Comment by mworrell** [comment]
Thank you!!
